services:
  execution:
    build:
      context: .
      dockerfile: Dockerfile.reth
    ports:
      - "8545:8545"       # RPC
      - "8546:8546"       # websocket
      - "7301:6060"       # metrics
    command: [ "bash", "./execution-entrypoint" ]
    volumes:
        - ${RETH_HOST_DATA_DIR}:/data
    env_file:
      # select your network here:
#      - .env.mainnet
#      - .env.sepolia
  node:
    build:
      context: .
      dockerfile: Dockerfile.reth
    depends_on:
      - execution
    ports:
      - "7545:8545"     # RPC
      - "9222:9222"     # P2P TCP
      - "9222:9222/udp" # P2P UDP
      - "7300:7300"     # metrics
      - "6060:6060"     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
      # select your network here:
#      - .env.mainnet
#      - .env.sepolia
