blank_issues_enabled: false
contact_links:
  - name: Base Documentation
    url: https://docs.base.org/
    about: Base is a secure, low-cost, developer-friendly Ethereum L2 built to bring the next billion users to web3.

